<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "hh_powermail_gdprlink"
 *
 * Auto generated by Extension Builder 2019-02-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF['hh_powermail_gdprlink'] = [
    'title' => 'Hauer-Heinrich powermail gdpr link',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Christian Hackl',
    'author_email' => 'web@hauer-heinrich.de',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '9.3.0-9.5.99',
            'extbase' => '9.3.0-9.5.99',
            'fluid' => '9.3.0-9.5.99',
            'powermail'=> '7.3.0-7.9.9'
        ],
        'conflicts' => [
        ],
        'suggests' => [
        ],
    ],
    'autoload' => [
        'psr-4' => [
            'HauerHeinrich\\HhPowermailGdprlink\\' => 'Classes'
        ],
    ],
];
